# Generated by Django 3.0.2 on 2020-03-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
