# Generated by Django 3.0.2 on 2020-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0006_auto_20200331_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
