# Generated by Django 3.0.2 on 2020-03-31 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0008_auto_20200331_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
