# Generated by Django 3.0.2 on 2020-03-31 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0009_auto_20200331_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
