# Generated by Django 3.0.2 on 2020-03-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0010_auto_20200331_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
