# Generated by Django 3.0.2 on 2020-04-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0011_auto_20200331_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=8192),
        ),
    ]
