# Generated by Django 3.0.2 on 2020-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0017_auto_20200403_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updates',
        ),
        migrations.DeleteModel(
            name='ProjectStat',
        ),
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
    ]
