# Generated by Django 3.0.2 on 2020-04-04 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0018_auto_20200404_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.CharField(max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='sky.Project')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
